/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projeto.matriz;

import static java.lang.System.console;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Thamires
 */
public class ProjetoMatriz extends javax.swing.JFrame {

    /**
     * Creates new form ProjetoMatriz
     */
    
    String[][] tabela = new String[10][3];
    int i = 0, j = 0;
    
    public ProjetoMatriz() {
        initComponents();
        painelcadastro.setVisible(false);
        pnlcampoobrigatorio1.setVisible(false);
        pnlcampoobrigatorio2.setVisible(false);
        pnlcampoobrigatorio3.setVisible(false);
    }

           
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        painelEntrada = new javax.swing.JPanel();
        lblentrada = new javax.swing.JLabel();
        btcadastro = new javax.swing.JButton();
        btnentradasair = new javax.swing.JButton();
        imagem = new javax.swing.JLabel();
        painelcadastro = new javax.swing.JPanel();
        lblnome = new javax.swing.JLabel();
        lblcidade = new javax.swing.JLabel();
        lblestado = new javax.swing.JLabel();
        txnome = new javax.swing.JTextField();
        txcidade = new javax.swing.JTextField();
        txestado = new javax.swing.JTextField();
        btsalvar = new javax.swing.JButton();
        btsair = new javax.swing.JButton();
        btimprimir = new javax.swing.JButton();
        pnlcampoobrigatorio1 = new javax.swing.JPanel();
        campobrigatorio1 = new javax.swing.JLabel();
        pnlcampoobrigatorio2 = new javax.swing.JPanel();
        campobrigatorio2 = new javax.swing.JLabel();
        pnlcampoobrigatorio3 = new javax.swing.JPanel();
        campobrigatorio3 = new javax.swing.JLabel();
        btvoltar = new javax.swing.JButton();
        imagemcadastro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelEntrada.setBackground(new java.awt.Color(153, 0, 255));
        painelEntrada.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblentrada.setBackground(new java.awt.Color(255, 255, 255));
        lblentrada.setFont(new java.awt.Font("Segoe UI Semibold", 0, 46)); // NOI18N
        lblentrada.setForeground(new java.awt.Color(153, 0, 204));
        lblentrada.setText("Bem Vindo");
        painelEntrada.add(lblentrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 260, 40));

        btcadastro.setBackground(new java.awt.Color(153, 0, 204));
        btcadastro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btcadastro.setForeground(new java.awt.Color(102, 0, 102));
        btcadastro.setText("Cadastrar");
        btcadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcadastroActionPerformed(evt);
            }
        });
        painelEntrada.add(btcadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, -1, -1));

        btnentradasair.setBackground(new java.awt.Color(204, 102, 255));
        btnentradasair.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnentradasair.setForeground(new java.awt.Color(102, 0, 102));
        btnentradasair.setText("Sair");
        btnentradasair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnentradasairActionPerformed(evt);
            }
        });
        painelEntrada.add(btnentradasair, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 60, 20));

        imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/WhatsApp Image 2024-09-27 at 09.39.25 (1).jpeg"))); // NOI18N
        painelEntrada.add(imagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 560));

        painelcadastro.setBackground(new java.awt.Color(255, 255, 255));
        painelcadastro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblnome.setBackground(new java.awt.Color(204, 204, 255));
        lblnome.setFont(new java.awt.Font("Source Serif Pro Semibold", 0, 14)); // NOI18N
        lblnome.setText("Nome:");
        painelcadastro.add(lblnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 49, 28));

        lblcidade.setBackground(new java.awt.Color(204, 204, 255));
        lblcidade.setFont(new java.awt.Font("Source Serif Pro Semibold", 0, 14)); // NOI18N
        lblcidade.setText("Cidade:");
        painelcadastro.add(lblcidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 49, 28));

        lblestado.setFont(new java.awt.Font("Source Serif Pro Semibold", 0, 14)); // NOI18N
        lblestado.setText("Estado:");
        painelcadastro.add(lblestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 49, 30));

        txnome.setBackground(new java.awt.Color(204, 153, 255));
        txnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txnomeActionPerformed(evt);
            }
        });
        painelcadastro.add(txnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 382, -1));

        txcidade.setBackground(new java.awt.Color(204, 153, 255));
        txcidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txcidadeActionPerformed(evt);
            }
        });
        painelcadastro.add(txcidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 267, -1));

        txestado.setBackground(new java.awt.Color(204, 153, 255));
        painelcadastro.add(txestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 170, -1));

        btsalvar.setBackground(new java.awt.Color(204, 102, 255));
        btsalvar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btsalvar.setForeground(new java.awt.Color(102, 0, 102));
        btsalvar.setText("Salvar");
        btsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsalvarActionPerformed(evt);
            }
        });
        painelcadastro.add(btsalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, 20));

        btsair.setBackground(new java.awt.Color(204, 102, 255));
        btsair.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btsair.setForeground(new java.awt.Color(102, 0, 102));
        btsair.setText("Sair");
        btsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsairActionPerformed(evt);
            }
        });
        painelcadastro.add(btsair, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, 70, 20));

        btimprimir.setBackground(new java.awt.Color(204, 102, 255));
        btimprimir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btimprimir.setForeground(new java.awt.Color(102, 0, 102));
        btimprimir.setText("Imprimir");
        btimprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btimprimirActionPerformed(evt);
            }
        });
        painelcadastro.add(btimprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, -1, 20));

        pnlcampoobrigatorio1.setBackground(new java.awt.Color(204, 204, 255));

        campobrigatorio1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        campobrigatorio1.setForeground(new java.awt.Color(204, 102, 255));
        campobrigatorio1.setText("Esse campo é obrigatório!");

        javax.swing.GroupLayout pnlcampoobrigatorio1Layout = new javax.swing.GroupLayout(pnlcampoobrigatorio1);
        pnlcampoobrigatorio1.setLayout(pnlcampoobrigatorio1Layout);
        pnlcampoobrigatorio1Layout.setHorizontalGroup(
            pnlcampoobrigatorio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlcampoobrigatorio1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(campobrigatorio1))
        );
        pnlcampoobrigatorio1Layout.setVerticalGroup(
            pnlcampoobrigatorio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlcampoobrigatorio1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(campobrigatorio1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        painelcadastro.add(pnlcampoobrigatorio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, -1, 23));

        pnlcampoobrigatorio2.setBackground(new java.awt.Color(204, 204, 255));

        campobrigatorio2.setBackground(new java.awt.Color(255, 255, 255));
        campobrigatorio2.setForeground(new java.awt.Color(204, 102, 255));
        campobrigatorio2.setText("Esse campo é obrigatório!");

        javax.swing.GroupLayout pnlcampoobrigatorio2Layout = new javax.swing.GroupLayout(pnlcampoobrigatorio2);
        pnlcampoobrigatorio2.setLayout(pnlcampoobrigatorio2Layout);
        pnlcampoobrigatorio2Layout.setHorizontalGroup(
            pnlcampoobrigatorio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlcampoobrigatorio2Layout.createSequentialGroup()
                .addComponent(campobrigatorio2)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        pnlcampoobrigatorio2Layout.setVerticalGroup(
            pnlcampoobrigatorio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlcampoobrigatorio2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(campobrigatorio2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        painelcadastro.add(pnlcampoobrigatorio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 140, 23));

        pnlcampoobrigatorio3.setBackground(new java.awt.Color(204, 204, 255));

        campobrigatorio3.setBackground(new java.awt.Color(255, 0, 102));
        campobrigatorio3.setForeground(new java.awt.Color(204, 102, 255));
        campobrigatorio3.setText("Esse campo é obrigatório!");

        javax.swing.GroupLayout pnlcampoobrigatorio3Layout = new javax.swing.GroupLayout(pnlcampoobrigatorio3);
        pnlcampoobrigatorio3.setLayout(pnlcampoobrigatorio3Layout);
        pnlcampoobrigatorio3Layout.setHorizontalGroup(
            pnlcampoobrigatorio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlcampoobrigatorio3Layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(campobrigatorio3))
        );
        pnlcampoobrigatorio3Layout.setVerticalGroup(
            pnlcampoobrigatorio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(campobrigatorio3, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
        );

        painelcadastro.add(pnlcampoobrigatorio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 140, 23));

        btvoltar.setBackground(new java.awt.Color(204, 102, 255));
        btvoltar.setForeground(new java.awt.Color(102, 0, 102));
        btvoltar.setText("Voltar");
        btvoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btvoltarActionPerformed(evt);
            }
        });
        painelcadastro.add(btvoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, -1, 20));

        imagemcadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/WhatsApp Image 2024-09-27 at 11.07.12.jpeg"))); // NOI18N
        painelcadastro.add(imagemcadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelcadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(painelEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelcadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(painelEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txcidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txcidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txcidadeActionPerformed

    private void btsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btsairActionPerformed

    private void btsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsalvarActionPerformed
         
        //Ver se todos os campos foram preenchidos
        
        if ((txnome.getText().trim().isEmpty()) || (txcidade.getText().trim().isEmpty()) || (txestado.getText().trim().isEmpty())) {
            JOptionPane.showMessageDialog(this, "Para realizar o cadastro, é necessário que TODOS os campos sejam preenchidos!");
            
            if (txnome.getText().trim().isEmpty()) {
                pnlcampoobrigatorio1.setVisible(true);
                if (txnome.getText().trim().isEmpty()) { // Coloca o foco se o campo estiver vazio
                txnome.requestFocus();}
                }
            
            else {
            pnlcampoobrigatorio1.setVisible(false); // Ocultar mensagem se o campo estiver preenchido
             }
            
            if (txcidade.getText().trim().isEmpty()) {
                pnlcampoobrigatorio2.setVisible(true);
                if (txcidade.getText().trim().isEmpty()) { // Coloca o foco se o campo estiver vazio
                txcidade.requestFocus();
                }
                
            }else {
            pnlcampoobrigatorio2.setVisible(false); // Ocultar mensagem se o campo estiver preenchido
            }   
            
            if (txestado.getText().trim().isEmpty()) {
                pnlcampoobrigatorio3.setVisible(true);
                if (txestado.getText().trim().isEmpty()) { // Coloca o foco se o campo estiver vazio
                txestado.requestFocus();
                }
                
            }else {
            pnlcampoobrigatorio3.setVisible(false); // Ocultar mensagem se o campo estiver preenchido
            }
            
            } 
            else {
            tabela[i][j] = txnome.getText();
            j++;
            tabela[i][j] = txcidade.getText();
            j++;
            tabela[i][j] = txestado.getText();
            j = 0; i++;
            
            //Quando clicar no botão de cadastro
            JOptionPane.showMessageDialog(this, "Os dados foram cadastrados");
            
            //Limpar o painel de cadastro
            txnome.setText(" ");
            txcidade.setText(" ");
            txestado.setText(" ");
            
            //Apagar o campo de mensagens obrigatórias
            
            pnlcampoobrigatorio1.setVisible(false);
            pnlcampoobrigatorio2.setVisible(false);
            pnlcampoobrigatorio3.setVisible(false);

        }
    }//GEN-LAST:event_btsalvarActionPerformed

    private void txnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txnomeActionPerformed
        JLabel nomeLabel = new JLabel("Nome:");
        nomeLabel.setBounds(10, 10, 80, 25);
        add(nomeLabel);
    }//GEN-LAST:event_txnomeActionPerformed

    private void btimprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btimprimirActionPerformed

       //Transformar matriz em string  
       
       String planilha = "";
    for (int i = 0; i < tabela.length; i++) {
        for (int j = 0; j < 3; j++) {
            if (tabela[i][j] == null) {
                planilha += " "; // Substitui "null" por "Campo vazio"
            } else {
                planilha += tabela[i][j];
                planilha += " - ";
            }
        }
        planilha += "\n-------------------------------------------------------------------------------------\n";
    }
    JOptionPane.showMessageDialog(null, planilha);
    System.out.println(planilha);
    
    }//GEN-LAST:event_btimprimirActionPerformed

    private void btcadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcadastroActionPerformed
       painelEntrada.setVisible(false);
       painelcadastro.setVisible(true);
    }//GEN-LAST:event_btcadastroActionPerformed

    private void btnentradasairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnentradasairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnentradasairActionPerformed

    private void btvoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btvoltarActionPerformed
        painelcadastro.setVisible(false);
        painelEntrada.setVisible(true);
        // Resetar a matriz para null
        i=0;
       for (int i = 0; i < tabela.length; i++) {
        for (int j = 0; j < tabela[i].length; j++) {
            tabela[i][j] = null; // Limpar cada célula da matriz
            
        }
    }
    }//GEN-LAST:event_btvoltarActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjetoMatriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjetoMatriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjetoMatriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjetoMatriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjetoMatriz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcadastro;
    private javax.swing.JButton btimprimir;
    private javax.swing.JButton btnentradasair;
    private javax.swing.JButton btsair;
    private javax.swing.JButton btsalvar;
    private javax.swing.JButton btvoltar;
    private javax.swing.JLabel campobrigatorio1;
    private javax.swing.JLabel campobrigatorio2;
    private javax.swing.JLabel campobrigatorio3;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel imagem;
    private javax.swing.JLabel imagemcadastro;
    private javax.swing.JLabel lblcidade;
    private javax.swing.JLabel lblentrada;
    private javax.swing.JLabel lblestado;
    private javax.swing.JLabel lblnome;
    private javax.swing.JPanel painelEntrada;
    private javax.swing.JPanel painelcadastro;
    private javax.swing.JPanel pnlcampoobrigatorio1;
    private javax.swing.JPanel pnlcampoobrigatorio2;
    private javax.swing.JPanel pnlcampoobrigatorio3;
    private javax.swing.JTextField txcidade;
    private javax.swing.JTextField txestado;
    private javax.swing.JTextField txnome;
    // End of variables declaration//GEN-END:variables
}
